clients:
- cluster: east
  headers:
    x-slate-destination: east
  method: POST
  path: /cart?product_id=OLJCESPC7Z&quantity=5
  retry:
    base: 1s
    count: 0
    factor: 2
    maxinterval: 5s
  rq_timeout: 5s
  workload:
  - duration: 1800s
    rps: 100
stats_output_folder: 9-19-nolimits-test-66injected/addtocart-W600-E100-bg50-interval45-delay66/SLATE-with-jumping-local
