clients:
- cluster: east
  headers:
    x-slate-destination: east
  method: POST
  path: /cart?product_id=OLJCESPC7Z&quantity=5
  workload:
  - duration: 600s
    rps: 500
  retry:
    base: 1s
    count: 0
    factor: 2
    maxinterval: 5s
  rq_timeout: 5s
stats_output_folder: test/addtocart-W500-E0/SLATE
