clients:
- cluster: west
  headers:
    x-slate-destination: west
  method: POST
  path: /cart?product_id=OLJCESPC7Z&quantity=5
  retry:
    base: 1s
    count: 0
    factor: 2
    maxinterval: 5s
  rq_timeout: 5s
  workload:
  - duration: 120s
    rps: 300
stats_output_folder: gangmuk-test-bg0/addtocart-W300/LOCAL
