clients:
- cluster: east
  headers:
    x-slate-destination: east
  method: POST
  path: /multicore
  retry:
    base: 1s
    count: 0
    factor: 2
    maxinterval: 5s
  rq_timeout: 15s
  workload:
  - duration: 60s
    rps: 200
  - duration: 120s
    rps: 300
stats_output_folder: corecontrast-reqtype-2/multicore-w50/SLATE-with-jumping-global
